export type Profile = { id: string; nickname: string; bio: string; avatar: number; status: string; created_at: string };
export type Sport = 'football' | 'basketball';
export type Event = { id: string; sport: Sport; league: string; home: string; away: string; starts_at: string; lock_at: string; status: string; source: string; is_demo: boolean };
export type Market = { id: string; event_id: string; code: string; label: string; status: string; line_value: number | null };
export type Selection = { id: string; market_id: string; code: string; label: string; odds: number; updated_at: string };
export type Pick = { id: string; user_id: string; event_id: string; market_id: string; selection_id: string; published_odds: number; analysis: string; status: string; published_at: string; settled_at: string | null; profit_units: number | null; published_hash: string; hidden: boolean };
export type Stats = Profile & { settled: number; wins: number; units: number; hit_rate: number; roi: number; average_odds: number; score: number; followers: number };
export type Notice = { id: string; title: string; href: string; type: string; read_at: string | null; created_at: string };
export type Audit = { id: string; recommendation_id: string; action: string; reason: string; old_value: Record<string, unknown> | null; new_value: Record<string, unknown>; created_at: string };
export type Snapshot = { profiles: Profile[]; events: Event[]; markets: Market[]; selections: Selection[]; picks: Pick[]; stats: Stats[]; following: string[]; notifications: Notice[]; audit: Audit[]; me: Profile | null; auth_id: string | null; role: string | null; in_app: boolean; demo: boolean; serverTime: number; demoAdmin: boolean };
export const statusLabels: Record<string,string> = { published: 'לפני המשחק', locked: 'ממתינה לתוצאה', won: 'הצליחה', lost: 'לא הצליחה', void: 'בוטלה', postponed: 'נדחתה', disputed: 'בבדיקה' };
export const sportLabels: Record<string,string> = { football: 'כדורגל', basketball: 'כדורסל' };
export function dateLabel(value: string, short = false) { return new Intl.DateTimeFormat('he-IL', { timeZone: 'Asia/Jerusalem', day: '2-digit', month: '2-digit', ...(short ? {} : {year:'numeric'}), hour:'2-digit', minute:'2-digit' }).format(new Date(value)); }
export function signed(value: number, suffix='') { return `${value>0?'+':''}${Number(value).toFixed(2)}${suffix}`; }
