import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {bootstrapSQL} from '../src/lib/demo-db';
let db:PGlite;const alice=randomUUID(),bob=randomUUID(),admin=randomUUID(),moderator=randomUUID();
async function rpc(name:string,p:unknown={},uid:string|null=alice,role=uid?'authenticated':'anon'){
 return db.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claim.role',$2,true)",[uid||'',role]);await tx.exec(`set local role ${role}`);const r=await tx.query<{data:Record<string,unknown>}>(`select public.${name}(${name==='process_jobs'?'':'$1::jsonb'}) data`,name==='process_jobs'?[]:[JSON.stringify(p)]);return r.rows[0].data;});
}
async function fixture({locked=false,odds=1.8}={}){const eid=randomUUID(),mid=randomUUID(),sid=randomUUID();await db.query("insert into public.events(id,sport,league,home,away,starts_at,lock_at,source,external_id,is_demo) values($1,'football','Test','A','B',now()+interval '1 hour',now()+($2||' minutes')::interval,'demo',$3,true)",[eid,locked?-1:58,eid]);await db.query("insert into public.markets(id,event_id,code,label) values($1,$2,'winner','תוצאה')",[mid,eid]);await db.query("insert into public.selections(id,market_id,code,label,odds) values($1,$2,'home','A',$3)",[sid,mid,odds]);return {eid,mid,sid,odds};}
async function publish(f:Awaited<ReturnType<typeof fixture>>,user=alice,key=randomUUID()){return rpc('publish_pick',{selection_id:f.sid,odds:f.odds,analysis:'בדיקה',key},user);}
beforeAll(async()=>{db=new PGlite();await db.exec(bootstrapSQL);await db.exec(await readFile('supabase/schema.sql','utf8'));for(const [id,nickname] of [[alice,'alice'],[bob,'bob'],[admin,'admin'],[moderator,'moderator']])await rpc('save_profile',{nickname,full_name:'Private Name',adult:true,terms:true,avatar:0},id);await db.query("insert into private.admins values($1,'admin'),($2,'moderator')",[admin,moderator]);});
afterAll(async()=>{await db.close();});
describe('publication invariants enforced by Postgres',()=>{
 it('rejects incomplete profile and anonymous publication',async()=>{const f=await fixture();await expect(publish(f,randomUUID())).rejects.toThrow('AUTH_REQUIRED');await expect(rpc('publish_pick',{},null)).rejects.toThrow();});
 it('rejects duplicate nickname case-insensitively and missing adult consent',async()=>{await expect(rpc('save_profile',{nickname:'ALICE',full_name:'Other',adult:true,terms:true},randomUUID())).rejects.toThrow();await expect(rpc('save_profile',{nickname:'newbie',full_name:'Other',adult:false,terms:true},randomUUID())).rejects.toThrow('PROFILE_INCOMPLETE');});
 it('rejects publication after the server cutoff',async()=>{await expect(publish(await fixture({locked:true}))).rejects.toThrow('EVENT_LOCKED');});
 it('rejects changed odds and snapshots the confirmed value',async()=>{const f=await fixture();await db.query('update public.selections set odds=2.1 where id=$1',[f.sid]);await expect(publish(f)).rejects.toThrow('ODDS_CHANGED');const p=await publish({...f,odds:2.1});await db.query('update public.selections set odds=3 where id=$1',[f.sid]);const r=await db.query<{published_odds:string}>('select published_odds from public.recommendations where id=$1',[p.id]);expect(Number(r.rows[0].published_odds)).toBe(2.1);});
 it('idempotently publishes and rejects a second selection in the same market',async()=>{const f=await fixture(),key=randomUUID();const first=await publish(f,alice,key);expect((await publish(f,alice,key)).id).toBe(first.id);await expect(publish(f)).rejects.toThrow('DUPLICATE_MARKET');const away=randomUUID();await db.query("insert into public.selections(id,market_id,code,label,odds) values($1,$2,'away','B',2)",[away,f.mid]);await expect(publish({...f,sid:away,odds:2})).rejects.toThrow('DUPLICATE_MARKET');});
 it('blocks direct update/delete and immutable payload changes even as owner',async()=>{const f=await fixture();const p=await publish(f);for(const sql of ['delete from public.recommendations','update public.recommendations set published_odds=4'])await expect(db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.exec(sql);})).rejects.toThrow();await expect(db.query('update public.recommendations set analysis=$1 where id=$2',['rewritten',p.id])).rejects.toThrow('PUBLISHED_IMMUTABLE');});
});
describe('settlement, statistics and audit',()=>{
 it('requires role and reason and rejects moderator override',async()=>{const f=await fixture();await publish(f);await expect(rpc('settle_market',{market_id:f.mid,winner:'home',reason:'test reason'})).rejects.toThrow('FORBIDDEN');await expect(rpc('settle_market',{market_id:f.mid,winner:'home',reason:'test reason',override:true},moderator)).rejects.toThrow('FORBIDDEN');await expect(rpc('settle_market',{market_id:f.mid,winner:'home',reason:''},admin)).rejects.toThrow('REASON_REQUIRED');});
 it('settles once, computes exact profit, and audits an override without deleting history',async()=>{const f=await fixture({odds:1.8});const p=await publish(f,bob);const input={market_id:f.mid,winner:'home',reason:'official test result'};await rpc('settle_market',input,admin);const audit=await db.query('select * from public.audit_logs where recommendation_id=$1',[p.id]);await rpc('settle_market',input,admin);expect((await db.query('select * from public.audit_logs where recommendation_id=$1',[p.id])).rows.length).toBe(audit.rows.length);const snap=await rpc('app_snapshot');const stats=(snap.stats as {id:string;units:number;roi:number;hit_rate:number;score:number}[]).find(s=>s.id===bob)!;expect(Number(stats.units)).toBe(.8);expect(Number(stats.roi)).toBe(80);expect(Number(stats.hit_rate)).toBe(100);expect(Number(stats.score)).toBeCloseTo(80/31,2);await rpc('settle_market',{...input,void:true,override:true},admin);const next=await rpc('app_snapshot');const st=(next.stats as {id:string;settled:number;units:number;roi:number}[]).find(s=>s.id===bob)!;expect(st.settled).toBe(0);expect(Number(st.units)).toBe(0);expect(Number(st.roi)).toBe(0);expect((await db.query('select * from public.audit_logs where recommendation_id=$1',[p.id])).rows.length).toBe(audit.rows.length+1);});
 it('calculates filtered periods by publication time and excludes voids/disputes',async()=>{const f=await fixture();const p=await publish(f,bob);await rpc('settle_market',{market_id:f.mid,winner:'home',reason:'valid source'},admin);await db.exec('alter table public.recommendations disable trigger immutable_pick');await db.query("update public.recommendations set published_at=now()-interval '45 days' where id=$1",[p.id]);await db.exec('alter table public.recommendations enable trigger immutable_pick');const all=await rpc('app_snapshot'),month=await rpc('app_snapshot',{days:'30'});const stat=(s:Record<string,unknown>)=>(s.stats as {id:string;settled:number}[]).find(x=>x.id===bob)!.settled;expect(stat(all)-stat(month)).toBe(1);});
 it('rejects direct audit modification',async()=>{await expect(db.exec("delete from public.audit_logs")).rejects.toThrow('AUDIT_IMMUTABLE');});
});
describe('privacy, following and permissions',()=>{
 it('keeps private information out of public snapshots and denies table reads across users',async()=>{const snap=await rpc('app_snapshot',{},null);expect(JSON.stringify(snap)).not.toContain('Private Name');expect(snap.me).toBeNull();expect(snap.notifications).toEqual([]);for(const table of ['private.accounts','private.admins','public.notifications'])await expect(db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.exec(`select * from ${table}`);})).rejects.toThrow();});
 it('deduplicates follows and notifications; self-follow is rejected',async()=>{await rpc('follow_user',{id:alice,follow:true},bob);await rpc('follow_user',{id:alice,follow:true},bob);expect((await db.query('select * from public.follows where follower_id=$1',[bob])).rows).toHaveLength(1);await expect(rpc('follow_user',{id:bob,follow:true},bob)).rejects.toThrow('SELF_FOLLOW');const f=await fixture();const p=await publish(f);await rpc('process_jobs',{},null,'service_role');await rpc('process_jobs',{},null,'service_role');expect((await db.query('select * from public.notifications where user_id=$1 and dedup_key=$2',[bob,'pick:'+p.id])).rows).toHaveLength(1);await rpc('follow_user',{id:alice,follow:false},bob);const next=await publish(await fixture());await rpc('process_jobs',{},null,'service_role');expect((await db.query('select * from public.notifications where user_id=$1 and dedup_key=$2',[bob,'pick:'+next.id])).rows).toHaveLength(0);});
 it('only marks the current users notifications read',async()=>{const id=randomUUID();await db.query("insert into public.notifications(id,user_id,type,title,href,dedup_key) values($1,$2,'test','private','/','test-read')",[id,alice]);await rpc('account_action',{action:'read',id},bob);expect((await db.query<{read_at:null}>('select read_at from public.notifications where id=$1',[id])).rows[0].read_at).toBeNull();});
 it('rejects admin actions from users and data changes from moderators',async()=>{await expect(rpc('admin_action',{action:'overview'})).rejects.toThrow('FORBIDDEN');await expect(rpc('admin_action',{action:'import',rows:[],reason:'test reason'},moderator)).rejects.toThrow('FORBIDDEN');});
});

describe('likes and winning streaks',()=>{
 it('deduplicates likes, protects identity and removes only the callers like',async()=>{const p=await publish(await fixture());await expect(rpc('like_pick',{id:p.id,liked:true},null)).rejects.toThrow();await rpc('like_pick',{id:p.id,liked:true},alice);await rpc('like_pick',{id:p.id,liked:true},alice);await rpc('like_pick',{id:p.id,liked:true},bob);let snap=await rpc('app_snapshot',{},null);expect((snap.likes as Record<string,number>)[String(p.id)]).toBe(2);expect(snap.liked).toEqual([]);await rpc('like_pick',{id:p.id,liked:false},alice);snap=await rpc('app_snapshot',{},bob);expect((snap.likes as Record<string,number>)[String(p.id)]).toBe(1);expect(snap.liked).toContain(p.id);await expect(db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.exec('select * from public.pick_likes');})).rejects.toThrow();});
 it('counts four consecutive wins, ignores voids and resets after a loss',async()=>{const uid=randomUUID();await rpc('save_profile',{nickname:'streak_test',full_name:'Test',adult:true,terms:true,avatar:0},uid);const streak=async()=>((await rpc('app_snapshot')).stats as {id:string;win_streak:number}[]).find(s=>s.id===uid)!.win_streak;for(let i=0;i<4;i++){const f=await fixture();await publish(f,uid);await rpc('settle_market',{market_id:f.mid,winner:'home',reason:'verified result'},admin);}expect(await streak()).toBe(4);const v=await fixture();await publish(v,uid);await rpc('settle_market',{market_id:v.mid,void:true,reason:'canceled fixture'},admin);expect(await streak()).toBe(4);const loss=await fixture(),away=randomUUID();await db.query("insert into public.selections(id,market_id,code,label,odds) values($1,$2,'away','B',2)",[away,loss.mid]);await publish(loss,uid);await rpc('settle_market',{market_id:loss.mid,winner:'away',reason:'verified loss'},admin);expect(await streak()).toBe(0);});
});
