'use client';
import {useEffect,useState} from 'react';
import {Upload,ShieldCheck,RefreshCw} from 'lucide-react';
import {useApp} from './context';
import {Empty} from './ui';
import {parseImport} from '@/lib/validation';
import {dateLabel} from '@/lib/types';
type Overview={reports:{id:string;reason:string;status:string;target_type:string;target_id:string}[];jobs:{id:string;attempts:number;last_error:string|null}[];runs:{id:string;provider:string;status:string;created_at:string}[]};
export function Admin(){const {data,act,toast}=useApp();const [tab,setTab]=useState('events'),[csv,setCsv]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[overview,setOverview]=useState<Overview|null>(null),[marketId,setMarket]=useState(''),[winner,setWinner]=useState(''),[isVoid,setVoid]=useState(false),[override,setOverride]=useState(false);
 useEffect(()=>{if(data.role)fetch('/api/action/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'overview'})}).then(r=>r.json()).then(r=>{if(r.reports)setOverview(r);});},[data.role]);
 if(!data.role)return <Empty title="אזור ניהול מוגן" body="נדרשת הרשאת צוות ייעודית. הרשאות משתמש רגיל אינן מאפשרות גישה."/>;
 const canData=['admin','data_operator'].includes(data.role),canModerate=['admin','moderator'].includes(data.role);const parsed=csv?parseImport(csv):null;
 async function run(action:string,p:unknown){setBusy(true);try{await act(action,p);toast('הפעולה הושלמה ונשמרה ביומן');if(action==='admin'&&(p as {action:string}).action==='import')setCsv('');}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 const pending=data.markets.filter(m=>m.status!=='settled'&&new Date(data.events.find(e=>e.id===m.event_id)!.starts_at).getTime()<data.serverTime);
 return <><div className="page-heading"><h1><ShieldCheck size={30}/>ניהול הקהילה</h1><p>נתונים, הכרעות ומודרציה · תפקיד: {data.role}</p></div><div className="admin-stats">{[[data.events.length,'אירועים'],[data.picks.filter(p=>['published','locked'].includes(p.status)).length,'המלצות פתוחות'],[pending.length,'שווקים בתור סגירה'],[overview?.jobs.length||0,'משימות התראה ממתינות']].map(([n,l])=><div className="panel" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="tabs admin-tabs">{[['events','אירועים ושווקים'],['settle','סגירת תוצאות'],['import','ייבוא CSV'],['users','משתמשים'],['reports','דיווחים'],['audit','יומן ביקורת'],['health','בריאות מערכת']].map(([v,l])=><button key={v} className={tab===v?'selected':''} onClick={()=>setTab(v)}>{l}</button>)}</div><div className="panel form-panel">
 {tab==='events'&&<><h2>אירועים ומקור נתונים</h2><div className="table-wrap"><table><thead><tr><th>אירוע</th><th>תחילה</th><th>מקור</th><th>סטטוס</th><th>שווקים</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{e.home} — {e.away}</td><td>{dateLabel(e.starts_at)}</td><td>{e.source}{e.is_demo?' · הדגמה':''}</td><td>{e.status}</td><td>{data.markets.filter(m=>m.event_id===e.id).map(m=><div key={m.id}>{m.label} · {m.status} · {data.selections.filter(s=>s.market_id===m.id).length} בחירות</div>)}</td></tr>)}</tbody></table></div></>}
 {tab==='import'&&(canData?<><h2>ייבוא אירועים, שווקים ויחסים</h2><p>הייבוא יתבצע רק לאחר בדיקת הקובץ והתצוגה המקדימה. <a href="/import-template.csv" download>הורדת תבנית CSV</a></p><label className="upload"><Upload/><span>בחירת קובץ CSV (עד 250KB)</span><input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>250000){toast('הקובץ גדול מדי');return;}setCsv(await f.text());}}/></label><label>או הדבקת CSV<textarea dir="ltr" rows={6} value={csv} onChange={e=>setCsv(e.target.value)}/></label>{parsed&&<><p>{parsed.rows.length} שורות זוהו</p>{parsed.errors.length?<div className="error-box" role="alert">{parsed.errors.map((e,i)=><div key={i}>{e}</div>)}</div>:<div className="success-box">הקובץ תקין. בדקו את התצוגה לפני אישור.</div>}<div className="table-wrap"><table><thead><tr><th>אירוע</th><th>שוק</th><th>בחירה</th><th>יחס</th></tr></thead><tbody>{parsed.rows.slice(0,20).map((r,i)=><tr key={i}><td>{r.home_participant} — {r.away_participant}</td><td>{r.market_code}</td><td>{r.selection_label_he}</td><td>{r.decimal_odds}</td></tr>)}</tbody></table></div></>}<label>מקור הנתונים וסיבת הייבוא<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5}/></label><button className="button primary" disabled={busy||!parsed||parsed.errors.length>0||reason.trim().length<5} onClick={()=>run('admin',{action:'import',csv,reason})}>אישור וייבוא {parsed?.rows.length||0} שורות</button></>:<p>נדרשת הרשאת מפעיל נתונים או מנהל.</p>)}
 {tab==='settle'&&(canData?<><h2>סגירת שוק ותיקון תוצאה</h2><p>יש להזין תוצאה ממקור מורשה. אין להסיק תוצאה מכתבה או מתוצאת חיפוש. {pending.length} שווקים ממתינים לטיפול.</p><label>שוק<select value={marketId} onChange={e=>{setMarket(e.target.value);setWinner('');}}><option value="">בחירת שוק</option>{data.markets.map(m=>{const e=data.events.find(e=>e.id===m.event_id)!;return <option key={m.id} value={m.id}>{e.home} — {e.away} · {m.label} · {m.status}</option>;})}</select></label><label>בחירה מנצחת<select value={winner} disabled={isVoid} onChange={e=>setWinner(e.target.value)}><option value="">בחירה</option>{data.selections.filter(s=>s.market_id===marketId).map(s=><option key={s.id} value={s.code}>{s.label}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={isVoid} onChange={e=>setVoid(e.target.checked)}/>ביטול השוק (Void) — אפס יחידות, ללא השפעה על ROI</label><label className="check-label"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>תיקון תוצאה שכבר נסגרה — יצירת Override פומבי</label><label>מקור וסיבה (חובה)<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button primary" disabled={busy||!marketId||(!winner&&!isVoid)||reason.trim().length<5} onClick={()=>run('settle',{market_id:marketId,winner,void:isVoid,override,reason,source:'manual'})}>שמירת תוצאה ועדכון ביצועים</button></>:<p>Moderators אינם רשאים לתקן תוצאות.</p>)}
 {tab==='users'&&<><h2>משתמשים</h2><label>סיבה לפעולת מודרציה<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{data.profiles.map(p=><div className="admin-row" key={p.id}><span>{p.nickname} · {p.status}</span>{canModerate&&p.id!==data.me?.id&&p.status!=='deleted'&&<button className="button outline" disabled={busy||reason.trim().length<5} onClick={()=>run('admin',{action:'suspend',id:p.id,suspend:p.status!=='suspended',reason})}>{p.status==='suspended'?'החזרת גישה':'השעיה'}</button>}</div>)}</>}
 {tab==='reports'&&<><h2>דיווחים</h2><label>סיבת טיפול<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{overview?.reports.map(r=><div className="admin-row" key={r.id}><span>{r.reason} · {r.status}</span>{canModerate&&<div><button className="button outline" disabled={busy||reason.trim().length<5} onClick={()=>run('admin',{action:'resolve',id:r.id,reason})}>סגירת דיווח</button>{r.target_type==='pick'&&<button className="button outline" disabled={busy||reason.trim().length<5} onClick={()=>run('admin',{action:'hide',id:r.target_id,reason})}>הסתרת תוכן</button>}</div>}</div>)}{!overview?.reports.length&&<Empty title="אין דיווחים פתוחים" body="דיווחים מהקהילה יופיעו כאן."/>}</>}
 {tab==='audit'&&<><h2>יומן ביקורת פומבי</h2>{data.audit.slice().reverse().slice(0,100).map(a=><div className="admin-row" key={a.id}><span>{a.action} · {a.reason}</span><time>{dateLabel(a.created_at)}</time></div>)}</>}
 {tab==='health'&&<><h2><RefreshCw size={20}/>בריאות מערכת</h2><p>מצב נתונים: {data.demo?'הדגמה מקומית · PostgreSQL משובץ':'Supabase · ייבוא ידני / ספק מורשה'}</p><p>אין ספק נתוני ספורט חי מחובר. יש להגדיר ספק מורשה לפני הפעלה עם נתוני אמת.</p><h3>משימות ממתינות / ניסיונות חוזרים</h3>{overview?.jobs.map(j=><p key={j.id}>{j.id} · ניסיונות {j.attempts} · {j.last_error||'ממתינה'}</p>)}<p>משימה שנכשלה חמש פעמים נשמרת לבדיקה ידנית. Cron מעבד התראות ונועל המלצות.</p></>}
 </div></>;
}
