'use client';
import {useState,useEffect,useRef} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import Script from 'next/script';
import {ArrowLeft,Smartphone,ShieldCheck,Check} from 'lucide-react';
import {browserAuth} from '@/lib/supabase/client';
import {useApp} from './context';
import {Avatar} from './ui';
type Turnstile={render:(element:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void};
export function Login(){const {data,refresh}=useApp(),router=useRouter();const [phone,setPhone]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[captcha,setCaptcha]=useState(''),[ready,setReady]=useState(false);const captchaRef=useRef<HTMLDivElement>(null);const siteKey=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
 useEffect(()=>{const t=(window as unknown as {turnstile?:Turnstile}).turnstile;if(!ready||!siteKey||!t||!captchaRef.current)return;const id=t.render(captchaRef.current,{sitekey:siteKey,callback:(token:string)=>setCaptcha(token),'expired-callback':()=>setCaptcha('')});return()=>t.remove(id);},[ready,siteKey]);
 async function demo(admin=false){setBusy(true);try{const res=await fetch('/api/demo-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({admin})});if(!res.ok)throw new Error('הכניסה לא הושלמה');await refresh();router.push(admin?'/admin':'/onboarding');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function google(){setBusy(true);const {error}=await browserAuth().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/auth/callback`}});if(error){setError('לא ניתן להתחבר ל־Google כרגע. נסו שוב.');setBusy(false);}}
 async function sms(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const normalized=phone.replace(/[\s-]/g,'').replace(/^0/,'+972');if(!/^\+[1-9]\d{7,14}$/.test(normalized))throw new Error('יש להזין מספר טלפון תקין, לדוגמה 0501234567.');const auth=browserAuth().auth;const result=sent?await auth.verifyOtp({phone:normalized,token:code,type:'sms'}):await auth.signInWithOtp({phone:normalized,options:{captchaToken:captcha||undefined}});if(result.error)throw new Error(sent?'הקוד לא תקין או שפג תוקפו. נסו שוב.':'לא ניתן לשלוח קוד כעת. בדקו את המספר ונסו שוב.');if(sent){await refresh();router.push('/onboarding');}else setSent(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="auth-page panel"><ShieldCheck size={38} className="teal"/><h1>ברוכים הבאים להמלצה.</h1><p>עוקבים, משתפים ובונים היסטוריה שאפשר לבדוק.</p>{error&&<div className="error-box" role="alert">{error}</div>}{data.demo?<><div className="notice">זוהי סביבת הדגמה מקומית. הכניסה יוצרת משתמש בדיקה נפרד, בלי Google או SMS אמיתיים.</div><button className="button primary wide" disabled={busy} onClick={()=>demo()}>כניסה להדגמה <ArrowLeft size={17}/></button>{data.demoAdmin&&<button className="button outline wide" disabled={busy} onClick={()=>demo(true)}>כניסת מנהל הדגמה</button>}</>:<><button className="button outline wide" onClick={google} disabled={busy}><span className="google-g">G</span>המשך עם Google</button><div className="or">או באמצעות הטלפון</div><form onSubmit={sms}><label>מספר טלפון<input type="tel" dir="ltr" value={phone} disabled={sent} onChange={e=>setPhone(e.target.value)} autoComplete="tel" placeholder="050 123 4567" required/></label>{sent&&<label>קוד חד־פעמי<input inputMode="numeric" autoComplete="one-time-code" dir="ltr" value={code} onChange={e=>setCode(e.target.value)} pattern="[0-9]{6}" maxLength={6} required/></label>}{siteKey&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" onLoad={()=>setReady(true)}/><div ref={captchaRef}/></>}<button className="button primary wide" disabled={busy||(!sent&&!!siteKey&&!captcha)}><Smartphone size={17}/>{busy?'רגע...':sent?'אימות וכניסה':'שליחת קוד ב־SMS'}</button>{sent&&<button className="button ghost" type="button" onClick={()=>setSent(false)}>שינוי מספר / בקשת קוד חדש</button>}</form></>}<p className="small-print">לבני 18 ומעלה בלבד. ההרשמה כפופה ל<Link href="/terms">תנאי השימוש</Link> ול<Link href="/privacy">מדיניות הפרטיות</Link>.</p></div>;
}
export function ProfileForm({onboarding=false}:{onboarding?:boolean}){const {data,act}=useApp(),router=useRouter();const [nickname,setNickname]=useState(data.me?.nickname||''),[bio,setBio]=useState(data.me?.bio||''),[avatar,setAvatar]=useState(data.me?.avatar||0),[fullName,setFullName]=useState(''),[adult,setAdult]=useState(false),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 if(!data.auth_id)return <Login/>;
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await act('profile',{nickname,bio,avatar,...(!data.me?{full_name:fullName,adult,terms}:{})});if(onboarding)router.push('/tipsters');else setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="settings-page"><div className="page-heading"><h1>{onboarding?'נעים להכיר. איך קוראים לך כאן?':'הפרופיל שלי'}</h1><p>{onboarding?'כינוי אחד, היסטוריה אחת. כל משתמש יכול לעקוב וגם להמליץ.':'הפרטים הציבוריים שמופיעים לצד ההמלצות שלך.'}</p></div>{!onboarding&&<div className="tabs"><Link className="selected" href="/settings/profile">פרופיל</Link><Link href="/settings/account">חשבון ופרטיות</Link></div>}<form className="panel form-panel" onSubmit={submit}>{error&&<div className="error-box" role="alert">{error}</div>}{saved&&<div className="success-box" role="status"><Check size={16}/>הפרופיל עודכן</div>}<label>כינוי ציבורי<input value={nickname} onChange={e=>setNickname(e.target.value)} minLength={3} maxLength={24} pattern="[a-zA-Z0-9א-ת_]{3,24}" required placeholder="למשל: זאב_צפוני"/><small>3–24 אותיות, ספרות או קו תחתון. שינוי אפשרי פעם ב־30 יום.</small></label>{!data.me&&<label>שם מלא (פרטי)<input value={fullName} onChange={e=>setFullName(e.target.value)} minLength={2} maxLength={100} autoComplete="name" required/><small>השם המלא אינו מוצג לציבור.</small></label>}<fieldset><legend>הפנים שלך בקהילה</legend><p className="muted">בחירה מתוך 20 אווטארים מקוריים</p><div className="avatar-grid">{Array.from({length:20},(_,i)=><button type="button" key={i} className={avatar===i?'selected':''} aria-label={`בחירת אווטאר ${i+1}`} aria-pressed={avatar===i} onClick={()=>setAvatar(i)}><Avatar profile={{avatar:i,nickname:`אווטאר ${i+1}`}} size={54}/>{avatar===i&&<Check size={14}/>}</button>)}</div></fieldset><label>כמה מילים עליך<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={300} rows={3} placeholder="ענפים, ליגות והגישה שלך לניתוח..."/></label>{!data.me&&<><label className="check-label"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)} required/>אני מצהיר/ה שמלאו לי 18 שנים.</label><label className="check-label"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} required/><span>קראתי ואני מסכים/ה ל<Link href="/terms">תנאי השימוש</Link> ול<Link href="/privacy">מדיניות הפרטיות</Link>.</span></label></>}<button className="button primary" disabled={busy}>{busy?'שומר...':onboarding?'יצירת פרופיל':'שמירת השינויים'}<ArrowLeft size={16}/></button></form></div>;
}
