'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,Check,LockKeyhole,ShieldCheck} from 'lucide-react';
import {useApp} from './context';
import {Empty} from './ui';
import {dateLabel} from '@/lib/types';
export function CreatePick(){const {data,act,refresh}=useApp(),router=useRouter();const [step,setStep]=useState(0),[sport,setSport]=useState('football'),[eventId,setEvent]=useState(''),[marketId,setMarket]=useState(''),[selectionId,setSelection]=useState(''),[odds,setOdds]=useState(0),[analysis,setAnalysis]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[key]=useState(()=>crypto.randomUUID());
 if(!data.me)return <Empty title="ההמלצה הראשונה מתחילה בפרופיל" body="התחברו וצרו פרופיל כדי לפרסם המלצות עם היסטוריה שאפשר לבדוק." href={data.auth_id?'/onboarding':'/login'} label={data.auth_id?'השלמת פרופיל':'כניסה ויצירת חשבון'}/>;
 const event=data.events.find(e=>e.id===eventId),market=data.markets.find(m=>m.id===marketId),selection=data.selections.find(s=>s.id===selectionId);
 const titles=['בחירת ענף','בחירת משחק','שוק ובחירה','הניתוח שלך','אישור ופרסום'];
 async function publish(){setBusy(true);setError('');try{const result=await act('publish',{selection_id:selectionId,odds,analysis,key});router.push(`/picks/${result.id}?published=1`);}catch(e){setError((e as Error).message);setConfirmed(false);await refresh();setStep(2);}finally{setBusy(false);}}
 return <div className="wizard"><div className="page-heading"><h1>ההמלצה שלך. ההיסטוריה שלך.</h1><p>בחירה אחת, מתועדת ושקופה.</p></div><div className="panel"><ol className="steps">{titles.map((t,i)=><li key={t} className={i<=step?'active':''}><span>{i<step?<Check size={15}/>:i+1}</span><small>{t}</small></li>)}</ol><div className="wizard-body"><div className="step-count">שלב {step+1} מתוך 5</div><h2>{titles[step]}</h2>{error&&<div className="error-box" role="alert">{error}</div>}
 {step===0&&<div className="sport-choices">{[['football','כדורגל','⚽'],['basketball','כדורסל','◉']].map(([value,label,icon])=><button className={`sport-choice ${sport===value?'selected':''}`} key={value} onClick={()=>{setSport(value);setEvent('');setMarket('');setSelection('');}}><span>{icon}</span><strong>{label}</strong></button>)}</div>}
 {step===1&&<div className="choice-list">{data.events.filter(e=>e.sport===sport&&e.status==='scheduled'&&new Date(e.lock_at).getTime()>data.serverTime).map(e=><button className={`choice ${eventId===e.id?'selected':''}`} key={e.id} onClick={()=>{setEvent(e.id);setMarket('');setSelection('');}}><span><small>{e.league}</small><strong>{e.home} — {e.away}</strong><small>{dateLabel(e.starts_at)} · שעון ישראל</small></span><span className="radio-dot"/></button>)}{!data.events.some(e=>e.sport===sport&&e.status==='scheduled'&&new Date(e.lock_at).getTime()>data.serverTime)&&<Empty title="אין משחקים פתוחים כרגע" body="משחקים נוספים יופיעו לאחר עדכון ספק הנתונים."/>}</div>}
 {step===2&&<><p>{event?.home} — {event?.away}</p><label>השוק<select value={marketId} onChange={e=>{setMarket(e.target.value);setSelection('');}}><option value="">בחירת שוק</option>{data.markets.filter(m=>m.event_id===eventId&&m.status==='open').map(m=><option key={m.id} value={m.id}>{m.label}{m.line_value!==null?` · ${m.line_value}`:''}</option>)}</select></label><div className="choice-list selections">{data.selections.filter(s=>s.market_id===marketId).map(s=><button className={`choice ${s.id===selectionId?'selected':''}`} key={s.id} onClick={()=>{setSelection(s.id);setOdds(Number(s.odds));setError('');}}><strong>{s.label}</strong><b dir="ltr">{Number(s.odds).toFixed(2)}</b></button>)}</div><p className="muted">היחס עשוי להשתנות. השרת יאמת אותו שוב ברגע הפרסום.</p></>}
 {step===3&&<><label>מה עומד מאחורי הבחירה? <span className="muted">(לא חובה)</span><textarea maxLength={600} rows={6} value={analysis} onChange={e=>setAnalysis(e.target.value)} placeholder="השיקולים, הנתונים והנקודות שכדאי לשים לב אליהם..."/></label><div className="counter">{analysis.length} / 600</div><p className="muted">כתבו ניתוח ענייני. בלי הבטחות זכייה ובלי המלצה על סכום כסף.</p></>}
 {step===4&&<><div className="review-summary"><small>{event?.league} · {dateLabel(event!.starts_at)}</small><h3>{event?.home} — {event?.away}</h3><div className="selection-strip"><div><span className="overline">{market?.label}</span><strong>{selection?.label}</strong></div><b dir="ltr">{odds.toFixed(2)}</b></div>{analysis&&<p>{analysis}</p>}</div><div className="notice"><LockKeyhole size={19}/><span>לאחר הפרסום לא ניתן לערוך או למחוק את ההמלצה. היחס והזמן יישמרו יחד עם הבחירה שלך.</span></div><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>בדקתי את הפרטים ואני מאשר/ת לפרסם ולנעול את ההמלצה.</label></>}
 </div><div className="wizard-actions">{step>0?<button className="button ghost" disabled={busy} onClick={()=>setStep(step-1)}><ArrowRight size={16}/>חזרה</button>:<Link className="button ghost" href="/feed">ביטול</Link>}{step<4?<button className="button primary" disabled={(step===1&&!eventId)||(step===2&&!selectionId)} onClick={()=>setStep(step+1)}>המשך<ArrowLeft size={16}/></button>:<button className="button primary" disabled={!confirmed||busy} onClick={publish}><LockKeyhole size={16}/>{busy?'מפרסם...':'פרסום ונעילת ההמלצה'}</button>}</div></div><p className="wizard-disclaimer"><ShieldCheck size={16}/>אין הבטחת זכייה. <Link href="/responsible-play">משחקים באחריות</Link></p></div>;
}
