'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,Check,LockKeyhole} from 'lucide-react';
import {useApp} from './context';
import {Empty} from './ui';
import {dateLabel} from '@/lib/types';
export function CreatePick(){const {data,act,refresh}=useApp(),router=useRouter();
 const [step,setStep]=useState(0),[sport,setSport]=useState('football'),[league,setLeague]=useState(''),[query,setQuery]=useState(''),[eventId,setEvent]=useState(''),[marketId,setMarket]=useState(''),[selectionId,setSelection]=useState(''),[odds,setOdds]=useState(0),[analysis,setAnalysis]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[key]=useState(()=>crypto.randomUUID());
 if(!data.me)return <Empty title="ההמלצה הראשונה מתחילה בפרופיל" body="התחברו וצרו פרופיל כדי לפרסם המלצות עם היסטוריה שאפשר לבדוק." href={data.auth_id?'/onboarding':'/login'} label={data.auth_id?'השלמת פרופיל':'כניסה ויצירת חשבון'}/>;
 const event=data.events.find(e=>e.id===eventId),selection=data.selections.find(s=>s.id===selectionId);
 const available=data.events.filter(e=>e.sport===sport&&e.status==='scheduled'&&new Date(e.lock_at).getTime()>data.serverTime&&data.markets.some(m=>m.event_id===e.id&&m.status==='open'));
 const matches=available.filter(e=>(!league||e.league===league)&&`${e.home} ${e.away} ${e.league}`.toLocaleLowerCase().includes(query.toLocaleLowerCase().trim()));
 function reset(){setEvent('');setMarket('');setSelection('');setConfirmed(false);}
 async function publish(){setBusy(true);setError('');try{const result=await act('publish',{selection_id:selectionId,odds,analysis,key});router.push(`/picks/${result.id}?published=1`);}catch(e){setError((e as Error).message);setConfirmed(false);setSelection('');await refresh();}finally{setBusy(false);}}
 return <div className="wizard"><div className="page-heading"><h1>מה ההמלצה שלך?</h1><p>מוצאים משחק, בוחרים המלצה ומפרסמים.</p></div><div className="panel"><ol className="steps">{['מציאת משחק','בחירה ופרסום'].map((title,i)=><li key={title} className={i<=step?'active':''}><span>{i<step?<Check size={15}/>:i+1}</span><small>{title}</small></li>)}</ol><div className="wizard-body"><div className="step-count">שלב {step+1} מתוך 2</div>{error&&<div className="error-box" role="alert">{error}</div>}
 {step===0?<><div className="find-match"><label>ענף<select value={sport} onChange={e=>{setSport(e.target.value);setLeague('');reset();}}><option value="football">כדורגל</option><option value="basketball">כדורסל</option></select></label><label>ליגה<select value={league} onChange={e=>{setLeague(e.target.value);reset();}}><option value="">כל הליגות</option>{[...new Set(available.map(e=>e.league))].map(l=><option key={l}>{l}</option>)}</select></label><label className="match-search">חיפוש משחק<input value={query} onChange={e=>{setQuery(e.target.value);reset();}} placeholder="שם קבוצה או ליגה"/></label></div><div className="choice-list">{matches.map(e=><button className={`choice ${eventId===e.id?'selected':''}`} key={e.id} onClick={()=>{setEvent(e.id);setMarket('');setSelection('');setConfirmed(false);}}><span><small>{e.league}</small><strong>{e.home} — {e.away}</strong><small>{dateLabel(e.starts_at)} · שעון ישראל</small></span><span className="radio-dot"/></button>)}{!matches.length&&<Empty title="לא נמצאו משחקים פתוחים" body="נסו לשנות את החיפוש או הסינון. משחקים נוספים יופיעו לאחר עדכון ספק הנתונים."/>}</div></>:<><div className="review-summary"><small>{event?.league} · {event&&dateLabel(event.starts_at)}</small><h2>{event?.home} — {event?.away}</h2></div><label>על מה ממליצים?<select value={marketId} onChange={e=>{setMarket(e.target.value);setSelection('');setConfirmed(false);}}><option value="">בחירת סוג המלצה</option>{data.markets.filter(m=>m.event_id===eventId&&m.status==='open').map(m=><option key={m.id} value={m.id}>{m.label}{m.line_value!==null?` · ${m.line_value}`:''}</option>)}</select></label><div className="choice-list selections">{data.selections.filter(s=>s.market_id===marketId).map(s=><button className={`choice ${s.id===selectionId?'selected':''}`} key={s.id} onClick={()=>{setSelection(s.id);setOdds(Number(s.odds));setConfirmed(false);setError('');}}><strong>{s.label}</strong><span><small>{event?.is_demo?'יחס הדגמה':event?.source==='winner'?'יחס Winner':'יחס המקור'}</small> <b dir="ltr">{Number(s.odds).toFixed(2)}</b></span></button>)}</div><label>ההמלצה שלך <span className="muted">(לא חובה)</span><textarea maxLength={600} rows={3} value={analysis} onChange={e=>{setAnalysis(e.target.value);setConfirmed(false);}} placeholder="לכו על ארסנל, היא תנצח היום! הנה למה..."/></label><div className="counter">{analysis.length} / 600</div><label className="check-label"><input type="checkbox" checked={confirmed} disabled={!selectionId} onChange={e=>setConfirmed(e.target.checked)}/>אני מאשר/ת לפרסם {selection?.label?`את הבחירה: ${selection.label}.`:'.'} לאחר הפרסום הבחירה, היחס והטקסט ננעלים.</label></>}
 </div><div className="wizard-actions">{step>0?<button className="button ghost" disabled={busy} onClick={()=>setStep(0)}><ArrowRight size={16}/>חזרה למשחקים</button>:<Link className="button ghost" href="/feed">ביטול</Link>}{step===0?<button className="button primary" disabled={!eventId} onClick={()=>setStep(1)}>בחירה והמלצה<ArrowLeft size={16}/></button>:<button className="button primary" disabled={!confirmed||!selectionId||busy} onClick={publish}><LockKeyhole size={16}/>{busy?'מפרסם...':'פרסום המלצה'}</button>}</div></div><p className="wizard-disclaimer">אין הבטחת זכייה. <Link href="/responsible-play">משחקים באחריות</Link></p></div>;
}
