'use client';
import Link from 'next/link';
import {Bell,CheckCheck,ShieldCheck,LockKeyhole} from 'lucide-react';
import {useApp} from './context';
import {PickCard} from './pick-card';
import {Empty} from './ui';
import {dateLabel} from '@/lib/types';
export function PickDetail({id}:{id:string}){const {data}=useApp();const pick=data.picks.find(p=>p.id===id);if(!pick)return <Empty title="ההמלצה לא נמצאה" body="בדקו את הקישור או חזרו לפיד." href="/feed" label="לפיד ההמלצות"/>;return <div className="detail-page"><Link className="back-link" href="/feed">חזרה להמלצות</Link><h1>המלצה אחת. כל הפרטים.</h1><PickCard pick={pick} detail/>{pick.event_id&&<section className="panel audit-panel"><h2><ShieldCheck size={22}/>יומן שקיפות</h2><p>פרטי הפרסום נשמרים. שינוי בתוצאה מתווסף ליומן ואינו מחליף את ההיסטוריה.</p><ol className="audit-list">{data.audit.filter(a=>a.recommendation_id===id).map(a=><li key={a.id}><span className="audit-dot"/><div><strong>{a.action==='published'?'פורסמה וננעלה':a.action==='override'?'תיקון מנהל':'התוצאה נסגרה'}</strong><time>{dateLabel(a.created_at)}</time><p>{a.reason}</p>{a.old_value&&<pre dir="ltr">{JSON.stringify(a.old_value)} → {JSON.stringify(a.new_value)}</pre>}</div></li>)}</ol><div className="hash"><LockKeyhole size={15}/><span>חתימת פרסום SHA-256</span><code dir="ltr">{pick.published_hash}</code></div></section>}</div>;}
export function Notifications(){const {data,act,toast}=useApp();if(!data.me)return <Empty title="כל העדכונים במקום אחד" body="התחברו כדי לראות המלצות חדשות ותוצאות." href="/login" label="כניסה"/>;return <div className="notifications-page"><div className="section-title"><div className="page-heading"><h1>ההתראות שלך</h1><p>המלצות חדשות, תוצאות ועדכונים מהקהילה.</p></div><button className="button outline" onClick={async()=>{try{await act('account',{action:'read',id:'all'});}catch(e){toast((e as Error).message);}}}><CheckCheck size={16}/>סימון הכול כנקרא</button></div><div className="panel">{data.notifications.map(n=><Link href={n.href} key={n.id} className={`notification-row ${n.read_at?'':'unread'}`} onClick={()=>{act('account',{action:'read',id:n.id}).catch(e=>toast(e.message));}}><span className="notice-icon"><Bell size={19}/></span><span><strong>{n.title}</strong><time>{dateLabel(n.created_at)}</time></span>{!n.read_at&&<i/>}</Link>)}{!data.notifications.length&&<Empty title="מעודכנים בהכול" body="כשתתפרסם המלצה של ממליץ שבמעקב, או שתיסגר המלצה שלך, העדכון יופיע כאן." href="/tipsters" label="לגלות ממליצים"/>}</div></div>;}
