'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,SlidersHorizontal,ShieldCheck} from 'lucide-react';
import {useApp} from './context';
import {Avatar,Empty,TrustPanel} from './ui';
import {PickCard} from './pick-card';
import {signed,statusLabels} from '@/lib/types';
export function Feed(){const {data}=useApp();const [tab,setTab]=useState('all'),[sport,setSport]=useState('all'),[league,setLeague]=useState('all'),[status,setStatus]=useState('all'),[sort,setSort]=useState('latest'),[day,setDay]=useState('all'),[limit,setLimit]=useState(12),[filters,setFilters]=useState(false);
 const picks=data.picks.filter(p=>{const e=data.events.find(e=>e.id===p.event_id)!;return (tab!=='following'||data.following.includes(p.user_id))&&(tab!=='settled'||['won','lost','void'].includes(p.status))&&(sport==='all'||e.sport===sport)&&(league==='all'||e.league===league)&&(status==='all'||p.status===status)&&(day==='all'||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(e.starts_at))===day);}).sort((a,b)=>sort==='upcoming'?new Date(data.events.find(e=>e.id===a.event_id)!.starts_at).getTime()-new Date(data.events.find(e=>e.id===b.event_id)!.starts_at).getTime():sort==='leaders'?(Number(data.stats.find(s=>s.id===b.user_id)?.score)||0)-(Number(data.stats.find(s=>s.id===a.user_id)?.score)||0):new Date(b.published_at).getTime()-new Date(a.published_at).getTime());
 const leaders=data.stats.filter(s=>s.settled>=30).slice(0,3);
 return <div className="feed-layout"><section className="feed-main"><div className="page-heading"><h1>המלצות עם קבלות<span>.</span></h1><p>כל המלצה מתועדת. כל תוצאה נספרת.</p></div><div className="feed-controls"><div className="tabs" role="tablist" aria-label="סוג פיד">{[['all','הכול'],['following','במעקב'],['settled','הסתיימו']].map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?'selected':''} onClick={()=>{setTab(value);setLimit(12);}}>{label}</button>)}</div><div className="filter-bar"><div className="sports">{[['all','כל הענפים'],['football','כדורגל'],['basketball','כדורסל']].map(([value,label])=><button key={value} className={`chip ${sport===value?'selected':''}`} onClick={()=>{setSport(value);setLeague('all');}}>{value==='football'?'⚽ ':value==='basketball'?'◉ ':''}{label}</button>)}</div><button className={`button small ${filters?'soft':'ghost'}`} onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={16}/>סינון</button></div>{filters&&<div className="advanced-filters"><label>ליגה<select value={league} onChange={e=>setLeague(e.target.value)}><option value="all">כל הליגות</option>{[...new Set(data.events.filter(e=>sport==='all'||e.sport===sport).map(e=>e.league))].map(l=><option key={l}>{l}</option>)}</select></label><label>סטטוס<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">כל הסטטוסים</option>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>מיון<select value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">חדש ביותר</option><option value="upcoming">משחקים קרובים</option><option value="leaders">ממליצים מובילים</option></select></label><label>תאריך משחק<input type="date" value={day==='all'?'':day} onChange={e=>setDay(e.target.value||'all')}/></label></div>}</div>
 <div className="feed-list">{picks.slice(0,limit).map(p=><PickCard key={p.id} pick={p}/>)}{!picks.length&&<Empty title={tab==='following'?'הפיד האישי שלך מתחיל כאן':'אין המלצות בסינון הזה'} body={tab==='following'?'עקבו אחרי ממליצים וההמלצות שלהם יופיעו כאן.':'אפשר לשנות את הסינון ולגלות המלצות נוספות.'} href={tab==='following'?'/tipsters':undefined} label="לגלות ממליצים"/>}{picks.length>limit&&<button className="button outline load-more" onClick={()=>setLimit(limit+12)}>הצגת המלצות נוספות</button>}</div></section>
 <aside className="sidebar"><section className="leaders"><div className="section-title"><h2>ממליצים בולטים</h2><Link href="/tipsters">לכל הדירוג <ArrowLeft size={14}/></Link></div><p className="muted">היסטוריה מלאה. מדגם של 30 תוצאות לפחות.</p>{leaders.map((s,i)=><Link href={`/tipsters/${s.nickname}`} className="leader-row" key={s.id}><span className="rank">{i+1}</span><Avatar profile={s} size={48}/><div><strong>{s.nickname.replaceAll('_',' ')}</strong><span className="positive" dir="ltr">{signed(Number(s.roi),'%')} ROI</span><small>{s.settled} המלצות שנסגרו</small></div></Link>)}{!leaders.length&&<p>הדירוג ייפתח כשיצטברו 30 תוצאות לממליץ.</p>}</section><TrustPanel/><div className="rail-note"><ShieldCheck size={18}/><p>מספרים, לא הבטחות.<br/>הצלחה בעבר אינה מבטיחה הצלחה בעתיד.</p></div></aside></div>;
}
