'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useApp} from './context';
import {Avatar,Empty,Follow} from './ui';
import {PickCard} from './pick-card';
export function Feed(){const {data}=useApp();const [tab,setTab]=useState('all'),[query,setQuery]=useState(''),[limit,setLimit]=useState(12);
 const picks=data.picks.filter(p=>(tab!=='following'||data.following.includes(p.user_id))&&(!query||(!p.hidden&&p.analysis.toLocaleLowerCase().includes(query.toLocaleLowerCase())))).sort((a,b)=>new Date(b.published_at).getTime()-new Date(a.published_at).getTime());
 return <div className="feed-layout"><section className="feed-main"><div className="page-heading"><h1>מדברים ספורט<span>.</span></h1><p>המלצות, דעות והקהילה שלך.</p></div><div className="feed-controls"><div className="tabs" role="tablist" aria-label="סוג פיד">{[['all','הכול'],['following','במעקב']].map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?'selected':''} onClick={()=>{setTab(value);setLimit(12);}}>{label}</button>)}</div><div className="filter-bar"><input aria-label="חיפוש בפוסטים" placeholder="חיפוש בפוסטים..." value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/></div></div><div className="feed-list">{picks.slice(0,limit).map(p=><PickCard key={p.id} pick={p}/>)}{!picks.length&&<Empty title="הפיד מחכה לפוסט הראשון" body="אפשר לפרסם המלצה או לעקוב אחרי ממליצים בקהילה." href="/create" label="כתיבת פוסט"/>}{picks.length>limit&&<button className="button outline" onClick={()=>setLimit(limit+12)}>עוד פוסטים</button>}</div></section><aside className="sidebar"><section className="leaders"><h2>אנשים בקהילה</h2>{data.profiles.filter(p=>p.status==='active'&&p.id!==data.me?.id).slice(0,5).map(p=><div className="leader-row" key={p.id}><Link className="table-user" href={`/tipsters/${p.nickname}`}><Avatar profile={p}/><strong>{p.nickname.replaceAll('_',' ')}</strong></Link><Follow id={p.id}/></div>)}<Link href="/tipsters">לכל הממליצים ←</Link></section><div className="rail-note"><p>משתפים דעות, לא מבטיחים זכיות. התוכן נכתב על ידי חברי הקהילה.</p></div></aside></div>;
}
