'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Info,Users,CalendarDays,Flag} from 'lucide-react';
import {useApp} from './context';
import {Avatar,Follow,Empty} from './ui';
import {PickCard} from './pick-card';
import {signed,dateLabel,type Stats} from '@/lib/types';
function Metrics({s}:{s:Stats}){return <div className="metrics">{[[`${s.settled}`,'המלצות שנסגרו'],[`${s.hit_rate}%`,'אחוז פגיעה'],[signed(Number(s.roi),'%'),'ROI'],[signed(Number(s.units),'u'),'רווח ביחידות'],[Number(s.average_odds).toFixed(2),'יחס ממוצע']].map(([value,label])=><div key={label}><strong dir="ltr">{value}</strong><span>{label}</span></div>)}</div>;}
export function Tipsters(){const {data,toast}=useApp();const [stats,setStats]=useState(data.stats);const [days,setDays]=useState('all'),[sport,setSport]=useState('all'),[league,setLeague]=useState('all'),[minimum,setMinimum]=useState(30),[sort,setSort]=useState('score'),[busy,setBusy]=useState(false);
 async function filter(next:{days?:string;sport?:string;league?:string}){const f={days,sport,league,...next};setDays(f.days);setSport(f.sport);setLeague(f.league);setBusy(true);try{const res=await fetch('/api/state?'+new URLSearchParams(f));const result=await res.json();if(!res.ok)throw new Error(result.message);setStats(result.stats);}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 const ranked=stats.filter(s=>s.settled>=Math.max(30,minimum)).sort((a,b)=>Number(b[sort as keyof Stats])-Number(a[sort as keyof Stats]));
 return <><div className="page-heading"><h1>המספרים מדברים<span>.</span></h1><p>ממליצים עם היסטוריה פתוחה, דירוג שקוף וכל התוצאות.</p></div><div className="panel"><div className="ranking-filters"><label>תקופה<select value={days} onChange={e=>filter({days:e.target.value})}><option value="all">כל הזמנים</option><option value="30">30 ימים</option><option value="90">90 ימים</option></select></label><label>ענף<select value={sport} onChange={e=>filter({sport:e.target.value,league:'all'})}><option value="all">כל הענפים</option><option value="football">כדורגל</option><option value="basketball">כדורסל</option></select></label><label>ליגה<select value={league} onChange={e=>filter({league:e.target.value})}><option value="all">כל הליגות</option>{[...new Set(data.events.filter(e=>sport==='all'||sport===e.sport).map(e=>e.league))].map(l=><option key={l}>{l}</option>)}</select></label><label>מינימום המלצות<select value={minimum} onChange={e=>setMinimum(Number(e.target.value))}><option value="30">30</option><option value="50">50</option><option value="100">100</option></select></label><label>מיון<select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">ציון דירוג</option><option value="roi">ROI</option><option value="hit_rate">אחוז פגיעה</option><option value="settled">מספר המלצות</option></select></label></div><p className="info-line"><Info size={16}/> ציון הדירוג = רווח ביחידות ÷ (תוצאות שנסגרו + 30) × 100. המדגם והתקופה הם חלק מהתמונה.</p><div className="table-wrap" aria-busy={busy}><table><thead><tr><th>#</th><th>ממליץ</th><th>ציון</th><th>פגיעה</th><th>ROI</th><th>יחידות</th><th>המלצות</th><th>יחס ממוצע</th><th>מעקב</th></tr></thead><tbody>{ranked.map((s,i)=><tr key={s.id}><td>{i+1}</td><td><Link className="table-user" href={`/tipsters/${s.nickname}`}><Avatar profile={s}/><strong>{s.nickname.replaceAll('_',' ')}</strong></Link></td><td>{s.score}</td><td>{s.hit_rate}%</td><td className={Number(s.roi)>=0?'positive':'negative'} dir="ltr">{signed(Number(s.roi),'%')}</td><td dir="ltr">{signed(Number(s.units))}</td><td>{s.settled}</td><td>{s.average_odds}</td><td><Follow id={s.id}/></td></tr>)}</tbody></table>{!ranked.length&&<Empty title="עדיין אין מדגם מספיק" body="במסננים שבחרת לא נמצאו ממליצים עם מספיק תוצאות לדירוג."/>}</div></div><h2 className="subheading">ממליצים חדשים · בדרך למדגם</h2><div className="new-tipsters">{stats.filter(s=>s.settled<30&&s.status!=='deleted').map(s=><div className="new-tipster" key={s.id}><Link className="table-user" href={`/tipsters/${s.nickname}`}><Avatar profile={s}/><span><strong>{s.nickname.replaceAll('_',' ')}</strong><small>{s.settled} מתוך 30 תוצאות לדירוג</small></span></Link><Follow id={s.id}/></div>)}</div></>;
}
export function ProfilePage({nickname}:{nickname:string}){const {data,act,toast}=useApp();const [status,setStatus]=useState('all'),[sport,setSport]=useState('all');const user=data.profiles.find(u=>u.nickname===nickname);if(!user)return <Empty title="הפרופיל לא נמצא" body="ייתכן שהכינוי השתנה." href="/tipsters" label="לכל הממליצים"/>;const s=data.stats.find(s=>s.id===user.id)!;const all=data.picks.filter(p=>p.user_id===user.id);const picks=all.filter(p=>(status==='all'||p.status===status)&&(sport==='all'||data.events.find(e=>e.id===p.event_id)?.sport===sport));
 const settled=all.filter(p=>['won','lost'].includes(p.status));let streak=0;for(const p of settled){if(p.status!==settled[0]?.status)break;streak++;}
 return <div className="profile-page"><section className="profile-header panel"><div className="profile-identity"><Avatar profile={user} size={88}/><div><h1>{nickname.replaceAll('_',' ')}</h1><p>{user.bio||'ההיסטוריה מתחילה בהמלצה הראשונה.'}</p><div className="profile-meta"><span><Users size={15}/>{s.followers} עוקבים</span><span><CalendarDays size={15}/>הצטרפות {dateLabel(user.created_at).split(',')[0]}</span></div></div><Follow id={user.id}/></div><Metrics s={s}/><p className="muted">{all.length} המלצות בסך הכול · רצף נוכחי: {streak} {settled[0]?.status==='won'?'הצלחות':'הפסדים'} · {s.settled<30?'ממתין למדגם של 30 תוצאות לדירוג':'מדגם מתאים לדירוג'}</p></section><div className="section-title"><h2>ההיסטוריה המלאה</h2><div className="inline-fields"><select aria-label="ענף בהיסטוריה" value={sport} onChange={e=>setSport(e.target.value)}><option value="all">כל הענפים</option><option value="football">כדורגל</option><option value="basketball">כדורסל</option></select><select aria-label="סטטוס בהיסטוריה" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">כל התוצאות</option><option value="won">הצלחות</option><option value="lost">הפסדים</option><option value="published">לפני משחק</option><option value="void">בוטלו</option></select></div></div><div className="feed-list">{picks.map(p=><PickCard pick={p} key={p.id}/>)}{!picks.length&&<Empty title="אין עדיין המלצות" body="כל המלצה שתפורסם תצטרף להיסטוריה כאן."/>}</div>{data.me&&<button className="button ghost" onClick={async()=>{const reason=prompt('מה הסיבה לדיווח על הפרופיל?');if(reason)try{await act('account',{action:'report',target_type:'profile',target_id:user.id,reason});toast('הדיווח נשלח');}catch(e){toast((e as Error).message);}}}><Flag size={15}/>דיווח על פרופיל</button>}</div>;
}
